name = spacecannon
title = Space Cannon
description = Adds five sci-fi/space cannons with various properties
depends = default, technic
optional_depends = digilines, mesecons, pipeworks
min_minetest_version = 5.10
